centro_reservas/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',Home.as_view(),name='home'),
    path('',Home.as_view(),name='index'),
    path('usuarios/',include('usuarios.urls',namespace='usuarios')),
    path('excursiones/',include('excursiones.urls',namespace='excursiones')),
    path('contacto/',include('contacto.urls',namespace='contacto')),
    path('administracion/',include('administracion.urls',namespace='administracion')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

contacto/urls.py
from django.urls import path
from .views import *

app_name = "contacto"

urlpatterns = [
    path('', Contacto.as_view(),name='contacto'),
    path('home/', ContactoHome.as_view(), name='contacto_home'),
]

excursiones/urls.py
from django.urls import path
from .views import *

app_name = "excursiones"

urlpatterns = [
    path('', ExcursionHome.as_view(),name='excursiones'),
    path('listar/', ExcursionList.as_view(),name='lista_excursiones'),
    path('crear/',ExcursionCreate.as_view(),name='crear_excursion'),
    path('editar/<int:pk>',ExcursionUpdate.as_view(),name='editar_excursion'),
    path('eliminar/<int:pk>',ExcursionDelete.as_view(),name='eliminar_excursion'),
    path('disponible/<int:pk>',disponible,name='disponible_excursion'),
]

templates/home/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}"/>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark sticky-top" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand fs-3" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse barra-navegacion-cliente" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link fs-3 ms-3 {% if 'home' in request.path %} active {% endif %}" href="{% url 'home' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-3 ms-3 {% if 'excursiones' in request.path %} active {% endif %}" href="{% url 'excursiones:excursiones' %}">Excursiones</a>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link fs-3 ms-3 {% if 'comentarios' in request.path %} active {% endif %}" href="#">Comentarios</a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link fs-3 ms-3 {% if 'contacto' in request.path %} active {% endif %}" href="{% url 'contacto:contacto' %}">Contacto</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    {% block contenido %}

    {% endblock contenido %}

    <footer class="bg-dark" style="color: whitesmoke">
      <div class="container">
          <div class="row">
              <div class="col-md-4" style="padding: 20px;">
                  <h2 class="fs-3">Texto 1 Cualquiera</h2>
                  <p class="fs-6">Los precios de las excursiones son por persona, incluyen IVA y están expresados en pesos argentinos excepto que se indique lo contrario; están sujetas a modificaciones sin previo aviso.</p>
              </div>
              <div class="col-md-4" style="padding: 20px;">
                  <h2 class="fs-3">Texto 2 Cualquiera</h2>
                  <p class="fs-6">Si durante la realización de un circuito turístico, ocurre algún caso fortuito o de fuerza mayor que imposibilite la concreción del mismo, la empresa no se responsabiliza por los tramos no efectuados.</p>
              </div>
              <div class="col-md-4" style="padding: 20px;">
                  <h2 class="fs-3">Texto 3 Cualquiera</h2>
                  <p class="fs-6">Alojamiento en las excursiones, comidas salvo las especificadas, entradas, extras en hoteles (bebidas, lavandería, llamadas telefónicas), tasas de aeropuerto, impuestos aéreos o cualquier otro gasto que surja de la necesidad personal.</p>
              </div>
          </div>
      </div>
  </footer>
  


    {% block js %}
      
    {% endblock js %}
      
    <script rel="stylesheet" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}


{% block js %}
<script>
        function loadContent(url) {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                // Crear un nuevo objeto DOMParser
                var parser = new DOMParser();
                // Parsear el this.responseText como un documento HTML
                var responseDoc = parser.parseFromString(this.responseText, "text/html");
                // Obtener el elemento con el ID "contacto" del documento parseado
                var contactoDiv = responseDoc.getElementById("contacto");
                // Verificar si se encontró el elemento "contacto"
                if (contactoDiv) {
                    // Obtener el contenido HTML del elemento "contacto"
                    var contactoHtml = contactoDiv.innerHTML;
                    // Insertar el contenido HTML en el elemento con el ID "contacto" en la página actual
                    document.getElementById("contacto").innerHTML = contactoHtml;
                }
            }
            };
            xhttp.open("GET", url, true);
            xhttp.send();
        }
    // Abrir y enviar la solicitud GET a la URL proporcionada
    loadContent("{% url 'contacto:contacto_home' %}");
</script>
{% endblock js %}
    

{% block contenido %}
<div class="d-flex justify-content-center align-items-center w-100" style="height: calc(100vh - 63.5px); background-image: url('{% static 'imagenes/cafayate.png' %}');background-size: cover; background-position: center;">
    <div class="glass-card d-flex flex-column justify-content-center align-items-center">    
        <h1 class="titulo">Excursiones Cafayate</h1>
        <p class="parrafo">
            Estamos encantados de recibirte en nuestra página web. Somos una empresa apasionada por la naturaleza y la belleza escénica de Cafayate, un lugar mágico y único en Argentina.<br>

            Nuestro objetivo es brindarte experiencias inolvidables en medio de paisajes impresionantes, viñedos interminables y formaciones rocosas que te dejarán sin aliento. Si estás buscando aventura, cultura y momentos de relajación en un entorno sin igual, has llegado al lugar correcto.</p>
    </div>
</div>
<div class="d-flex flex-column justify-content-center align-items-center w-100" style="height: calc(100vh - 63.5px);">
    <h1 class="fs-1">Excursiones Cafayate</h1>
    <p class="text-center  w-75 fs-5">Desde recorridos por bodegas boutique con degustaciones de vinos exquisitos hasta aventuras en bicicleta por los valles más asombrosos, nuestras opciones están pensadas para que cada momento con nosotros sea especial y memorable.</p>
    <div class="galeria">
        <img src="{% static 'imagenes/1.png' %}" alt="">
        <img src="{% static 'imagenes/2.png' %}" alt="">
        <img src="{% static 'imagenes/3.png' %}" alt="">
        <img src="{% static 'imagenes/4.png' %}" alt="">
        <img src="{% static 'imagenes/5.png' %}" alt="">
    </div>
</div>
    
<div class="d-flex justify-content-center align-items-center w-100" id="contacto" style="background-image: url('{% static 'imagenes/cafayate.png' %}');background-size: cover; background-position: center;">
    <div class="glass-card">
        <h1 class="fs-1 text-center mt-3" style="color:white;">Contáctanos!</h1>    
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="botones btn">Enviar</button>
        </form>
    </div>
</div>
{% endblock contenido %}
    