administracion/urls.py
from django.urls import path
from .views import *

app_name = "administracion"

urlpatterns = [
    path('', Home.as_view(),name='home'),
]

centro_reservas/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',Home.as_view(),name='home'),
    path('',Home.as_view(),name='index'),
    path('usuarios/',include('usuarios.urls',namespace='usuarios')),
    path('excursiones/',include('excursiones.urls',namespace='excursiones')),
    path('contacto/',include('contacto.urls',namespace='contacto')),
    path('administracion/',include('administracion.urls',namespace='administracion')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

contacto/urls.py
from django.urls import path
from .views import *

app_name = "contacto"

urlpatterns = [
    path('', Contacto.as_view(),name='contacto'),
    path('home/', ContactoHome.as_view(), name='contacto_home'),
]

administracion/models.py
from django.db import models

# Create your models here.

administracion/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class Home(TemplateView):
    template_name= 'administracion/home.html'

templates/administracion/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}"/>
    
    {% block head %}
        
    {% endblock head %}
        
</head>
<body>
    
    
<nav class="container-fluid">
    <div class="row">
        <div class="col-sm-auto bg-dark sticky-top">
            <div class="d-flex flex-sm-column flex-row flex-nowrap bg-dark align-items-center sticky-top">
                <a href="{% url 'administracion:home' %}" class="d-block p-3 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
                    <i class="bi-bootstrap fs-1" style="color:{% if 'administracion' in request.path %} white {% else %} rgba(255, 255, 255, 0.5) {% endif %};"></i>
                </a>
                <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center align-items-center">
                    <li class="nav-item">
                        <a href="{% url 'administracion:home' %}" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
                            <i class="bi-house fs-1" style="color:{% if 'administracion' in request.path %} white {% else %} rgba(255, 255, 255, 0.5) {% endif %};"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Dashboard">
                            <i class="bi-speedometer2 fs-1" style="color:{% if 'excursiones' in request.path %} white {% else %} rgba(255, 255, 255, 0.5) {% endif %};"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Orders">
                            <i class="bi-table fs-1" style="color:{% if 'actividades' in request.path %} white {% else %} rgba(255, 255, 255, 0.5) {% endif %};"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Products">
                            <i class="bi-heart fs-1" style="color:{% if 'admip' in request.path %} white {% else %} rgba(255, 255, 255, 0.5) {% endif %};"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Customers">
                            <i class="bi-people fs-1" style="color:{% if 'usuarios' in request.path %} white {% else %} rgba(255, 255, 255, 0.5) {% endif %};"></i>
                        </a>
                    </li>
                </ul>
                <div class="dropdown">
                    <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi-person-circle h2" style="color: white;"></i>
                    </a>
                    <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
                        <li><a class="dropdown-item" href="#">Modificar Datos</a></li>
                        <li><a class="dropdown-item" href="#">Cerrar Sesión</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-sm p-3 min-vh-100">
            {% block contenido %}
        
            {% endblock contenido %}
        </div>
    </div>
</nav>    

    <script rel="stylesheet" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    
    {% block js %}
        
    {% endblock js %}
        
</body>
</html>